### ISSUE TITLE
THIS PROJECT IS BROKEN

### ISSUE THREAD

**Issue by mmontag** [vsetka/deepl-translator-cli#4] opened 2019-11-22 18:06 UTC
Warning for others. @vsetka, please close the issue if I'm wrong. 
`deepl-translate(1) does not exist, try --help`

**Comment by bserem** [comment] 2020-01-23 14:16
Duplicate of #3

**Comment by return42** [comment] 2020-01-24 06:14
https://github.com/vsetka/deepl-translator-cli/issues/2#issuecomment-383504283

> Workaround https://github.com/uinput/deeplator

**Comment by vsetka** [comment] 2024-12-09 04:14
Repository no longer maintained

**Closed as completed by vsetka** 2024-12-09 04:14 UTC
